### ISSUE TITLE
clone redundant?

### ISSUE THREAD

**Issue by benma** [async-rs/async-task#23]
Running clippy warns that this clone is redundant:

https://github.com/async-rs/async-task/blob/b7a249680490991f92cc2144d4eff65e4effb3b7/src/waker_fn.rs#L26

True or false?

Thanks

**Comment by ghost** [comment]
No, this clone and forget is necessary to bump the reference counter. This won't be necessary anymore when this feature gets stabilized: https://github.com/rust-lang/rust/pull/70733

**Comment by benma** [comment]
Thanks!
